/**
 * TypeScript declaration file for Create React App
 * 
 * This file is automatically generated by create-react-app when TypeScript
 * is detected in a project. It references the type definitions for the
 * react-scripts package, which includes all the ambient types needed for
 * a Create React App project, including:
 * 
 * - Static file imports (.svg, .png, etc.)
 * - CSS/SCSS module imports
 * - Environment variables defined in .env files
 * - Service worker registration
 */
/// <reference types="react-scripts" />